apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helmfile-master
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://api.lillypilly.asci.synchrotron.org.au:6443
  project: default
  source:
    path: test-app/releases/master
    plugin:
      name: helmfile
    repoURL: https://github.com/m33m33k/playground
    targetRevision: master
